remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Doc4TF
description: Python script running in Jupyter Notebook to create feature documentation set for Text-Fabric.
show_downloads: true
