remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap

title: Doc4TF
description: Python script running in Jupyter Notebook to create feature documentation set for Text-Fabric.
keywords: "Text-Fabric,feature documentation,dataset exploration"
show_downloads: true
